<?php

########################################################################
# Extension Manager/Repository config file for ext: "dl_voucher"
#
# Auto generated by Extension Builder 2011-11-20
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Order a Voucher',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Daniel Lienert',
	'author_email' => 'daniel@lienert.cc',
	'author_company' => 'Daniel Lienert',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>